/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.96
 * Generated at: 2019-11-06 13:46:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.boot;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/boot/include.jsp", Long.valueOf(1573047933770L));
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("  <meta name=\"description\" content=\"\">\r\n");
      out.write("  <meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("  <title>로그인화면</title>\r\n");
      out.write("\r\n");
      out.write("  <!-- Bootstrap core CSS -->\r\n");
      out.write("  <link href=\"vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Custom styles for this template -->\r\n");
      out.write("  <link href=\"css/shop-homepage.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write(" ");
      out.write("\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("  <meta name=\"description\" content=\"\">\r\n");
      out.write("  <meta name=\"author\" content=\"\">\r\n");
      out.write("<script src=\"vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("  <title>메인 홈 화면</title>\r\n");
      out.write("\r\n");
      out.write("  <!-- Bootstrap core CSS -->\r\n");
      out.write("  <link href=\"vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Custom styles for this template -->\r\n");
      out.write("  <link href=\"css/shop-homepage.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("  <!-- Navigation -->\r\n");
      out.write("  <nav class=\"navbar navbar-expand-lg navbar-dark bg-dark fixed-top\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("    <img src='main1.png' class=\"navbar-brand\" href=\"index.jsp\"> \r\n");
      out.write("  <a class=\"navbar-brand\" href=\"index.jsp\">커픽</a>\r\n");
      out.write("      <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarResponsive\" aria-controls=\"navbarResponsive\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("        <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("      </button>\r\n");
      out.write("      <div class=\"collapse navbar-collapse\" id=\"navbarResponsive\">\r\n");
      out.write("        <ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("      <!-- 불들어오는거 --> <!--    <li class=\"nav-item active\"> -->\r\n");
      out.write("            <a class=\"nav-link\" href=\"index.jsp\">홈\r\n");
      out.write("\r\n");
      out.write("              <span class=\"sr-only\">(current)</span>\r\n");
      out.write("\r\n");
      out.write("            </a>\r\n");
      out.write("          </li>   \r\n");
      out.write("          <!--  -->\r\n");
      out.write("            <a class=\"nav-link\" data-toggle=\"tooltip\" title=\"login!\" href=\"login.jsp\">로그인</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link\" href=\"notice.jsp\">커픽장터</a>\r\n");
      out.write("             <li class=\"nav-item\">\r\n");
      out.write("                       <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link\" href=\"tkdvna.jsp\">커피정보</a>\r\n");
      out.write("          </li>\r\n");
      out.write("            <a class=\"nav-link\" href=\"qwe1.jsp\">가맹점 위치</a>\r\n");
      out.write("          </li>\r\n");
      out.write("           <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link\" href=\"qwe2.jsp\">카페검색</a>\r\n");
      out.write("              <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link\" href=\"Coffe1.jsp\">맞춤 음료</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link\" href=\"#\">마이페이지</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          \r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </nav>\r\n");
      out.write("\r\n");
      out.write("  <!-- Page Content -->\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("      <div class=\"col-lg-3\">\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("      <!--   <h5 class=\"my-4\">커피 원두 선택&예약 </h5> -->\r\n");
      out.write("     <!--    <div class=\"list-group\">\r\n");
      out.write("          <a href=\"#\" class=\"list-group-item\">맞춤커피</a>\r\n");
      out.write("          <a href=\"#\" class=\"list-group-item\">카페위치</a>\r\n");
      out.write("          <a href=\"#\" class=\"list-group-item\">이벤트</a>\r\n");
      out.write("        </div>  -->\r\n");
      out.write("\r\n");
      out.write("   </div>\r\n");
      out.write("   </div>\r\n");
      out.write("   </div>\r\n");
      out.write("  \r\n");
      out.write("      \r\n");
      out.write("      </body>\r\n");
      out.write("\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            \r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\t<div class=\"row text-center mb-4\">\r\n");
      out.write("\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t    <!-- <h4>커픽</h4>\r\n");
      out.write("\t\t    <small>09.20</small> -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"row text-center\">\r\n");
      out.write("\t    <div class=\"col-md-6 offset-md-3\">\r\n");
      out.write("\t        <div class=\"card\">\r\n");
      out.write("\t            <div class=\"card-body\">\r\n");
      out.write("\t                <div class=\"login-img\">\r\n");
      out.write("<!-- 로그인화면 이미지 넣는거 -->  <img src='log1.png'>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t                <!-- <div class=\"login-title\">\r\n");
      out.write("\t                    <h4>로그인</h4>\r\n");
      out.write("\t                </div> -->\r\n");
      out.write("\t                <div class=\"login-form mt-4\">\r\n");
      out.write("\t                    <form>\r\n");
      out.write("                        <div class=\"form-row\">\r\n");
      out.write("                            <div class=\"form-group col-md-12\">\r\n");
      out.write("                              <input id=\"email\" name=\"Full Name\" placeholder=\"아이디\" class=\"form-control\" type=\"text\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"form-group col-md-12\">\r\n");
      out.write("                              <input type=\"pass\" class=\"form-control\" id=\"pass\" placeholder=\"비밀번호\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                          </div>\r\n");
      out.write("                         <div class=\"form-row\">\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                                <div class=\"form-check\">\r\n");
      out.write("                                  <input class=\"form-check-input\" type=\"checkbox\" value=\"\" id=\"updatecheck1\">\r\n");
      out.write("                                  <label class=\"form-check-label\" for=\"updatecheck1\">\r\n");
      out.write("                                    <small>아이디 저장 <a href=\"#\">약관보기 </a> </small>\r\n");
      out.write("                                    \r\n");
      out.write("                                  </label>\r\n");
      out.write("                                </div>\r\n");
      out.write("                              </div>\r\n");
      out.write("                    </div>                        \r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"form-row\">\r\n");
      out.write("                            <button type=\"button\" class=\"btn btn-danger btn-block\">로그인</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </form>\r\n");
      out.write("                     <br>\r\n");
      out.write("                     <div class=\"logi-forgot\">\r\n");
      out.write("\t                    <a href=\"#\">회원가입 </a>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t                <div class=\"logi-forgot text-right mt-2\">\r\n");
      out.write("\t                    <a href=\"#\">아이디, 비밀번호 찾기 </a>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <!-- Footer -->\r\n");
      out.write(" <!--  <footer class=\"py-5 bg-dark\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <p class=\"m-0 text-center text-white\">6조 일찍끝내조 &copy; 이재훈, 정회석, 이혜지</p>\r\n");
      out.write("    </div>\r\n");
      out.write("    /.container\r\n");
      out.write("  </footer> -->\r\n");
      out.write("\r\n");
      out.write("  <!-- Bootstrap core JavaScript -->\r\n");
      out.write("  <script src=\"vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
