/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.96
 * Generated at: 2019-11-07 08:06:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.boot;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class qwe1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/boot/include.jsp", Long.valueOf(1573047933770L));
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("  <meta name=\"description\" content=\"\">\r\n");
      out.write("  <meta name=\"author\" content=\"\">\r\n");
      out.write("\t<meta charset=\"utf-8\"/>\r\n");
      out.write("\t<title>가맹점 위치</title>\r\n");
      out.write("\t<!-- Bootstrap core CSS -->\r\n");
      out.write("  <link href=\"vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Custom styles for this template -->\r\n");
      out.write("  <link href=\"css/shop-homepage.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("  <meta name=\"description\" content=\"\">\r\n");
      out.write("  <meta name=\"author\" content=\"\">\r\n");
      out.write("<script src=\"vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("  <title>메인 홈 화면</title>\r\n");
      out.write("\r\n");
      out.write("  <!-- Bootstrap core CSS -->\r\n");
      out.write("  <link href=\"vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Custom styles for this template -->\r\n");
      out.write("  <link href=\"css/shop-homepage.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("  <!-- Navigation -->\r\n");
      out.write("  <nav class=\"navbar navbar-expand-lg navbar-dark bg-dark fixed-top\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("    <img src='main1.png' class=\"navbar-brand\" href=\"index.jsp\"> \r\n");
      out.write("  <a class=\"navbar-brand\" href=\"index.jsp\">커픽</a>\r\n");
      out.write("      <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarResponsive\" aria-controls=\"navbarResponsive\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("        <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("      </button>\r\n");
      out.write("      <div class=\"collapse navbar-collapse\" id=\"navbarResponsive\">\r\n");
      out.write("        <ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("      <!-- 불들어오는거 --> <!--    <li class=\"nav-item active\"> -->\r\n");
      out.write("            <a class=\"nav-link\" href=\"index.jsp\">홈\r\n");
      out.write("\r\n");
      out.write("              <span class=\"sr-only\">(current)</span>\r\n");
      out.write("\r\n");
      out.write("            </a>\r\n");
      out.write("          </li>   \r\n");
      out.write("          <!--  -->\r\n");
      out.write("            <a class=\"nav-link\" data-toggle=\"tooltip\" title=\"login!\" href=\"login.jsp\">로그인</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link\" href=\"notice.jsp\">커픽장터</a>\r\n");
      out.write("             <li class=\"nav-item\">\r\n");
      out.write("                       <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link\" href=\"tkdvna.jsp\">커피정보</a>\r\n");
      out.write("          </li>\r\n");
      out.write("            <a class=\"nav-link\" href=\"qwe1.jsp\">가맹점 위치</a>\r\n");
      out.write("          </li>\r\n");
      out.write("           <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link\" href=\"qwe2.jsp\">카페검색</a>\r\n");
      out.write("              <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link\" href=\"Coffe1.jsp\">맞춤 음료</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link\" href=\"#\">마이페이지</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          \r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </nav>\r\n");
      out.write("\r\n");
      out.write("  <!-- Page Content -->\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("      <div class=\"col-lg-3\">\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("      <!--   <h5 class=\"my-4\">커피 원두 선택&예약 </h5> -->\r\n");
      out.write("     <!--    <div class=\"list-group\">\r\n");
      out.write("          <a href=\"#\" class=\"list-group-item\">맞춤커피</a>\r\n");
      out.write("          <a href=\"#\" class=\"list-group-item\">카페위치</a>\r\n");
      out.write("          <a href=\"#\" class=\"list-group-item\">이벤트</a>\r\n");
      out.write("        </div>  -->\r\n");
      out.write("\r\n");
      out.write("   </div>\r\n");
      out.write("   </div>\r\n");
      out.write("   </div>\r\n");
      out.write("  \r\n");
      out.write("      \r\n");
      out.write("      </body>\r\n");
      out.write("\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t<h1 align=\"center\">가맹점 위치</h1>\r\n");
      out.write("    <div id=\"map\" style=\"width:800px;height:600px;\"></div>\r\n");
      out.write("    \r\n");
      out.write("\t<script type=\"text/javascript\" src=\"//dapi.kakao.com/v2/maps/sdk.js?appkey=18273b220eba4bfbc04f68bed4f99964\"></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("  var container = document.getElementById('map');\r\n");
      out.write("  var options = {\r\n");
      out.write("  center: new kakao.maps.LatLng(37.58988628988218,\t127.05810731647018),\r\n");
      out.write("  level: 3\r\n");
      out.write("  };\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  var map = new kakao.maps.Map(container, options);\r\n");
      out.write("  \r\n");
      out.write("  var positions = [\r\n");
      out.write("      { latlng: new kakao.maps.LatLng(37.588859714142586,\t127.06564156980917)},\r\n");
      out.write("      { latlng: new kakao.maps.LatLng(37.58942230957589,\t127.06245761740055)},\r\n");
      out.write("      { latlng: new kakao.maps.LatLng(37.58990462015859,\t127.05747326793112)},\r\n");
      out.write("      { latlng: new kakao.maps.LatLng(37.58982830195359,\t127.0569240661392)},\r\n");
      out.write("      { latlng: new kakao.maps.LatLng(37.58958412401539,\t127.05878077038038)},\r\n");
      out.write("      { latlng: new kakao.maps.LatLng(37.58901571062146,\t127.0603428166437)},\r\n");
      out.write("      { latlng: new kakao.maps.LatLng(37.5895385,\t127.0590682,17.56)},\r\n");
      out.write("      { latlng: new kakao.maps.LatLng(37.5897228,127.0561061,17.56)},\r\n");
      out.write("      { latlng: new kakao.maps.LatLng(37.5885125,127.0512045,16)},\r\n");
      out.write("      { latlng: new kakao.maps.LatLng(37.5774663,127.0458377,15.52)},\r\n");
      out.write("      { latlng: new kakao.maps.LatLng(37.5897357,127.0448379,15.52)},\r\n");
      out.write("      { latlng: new kakao.maps.LatLng(37.583691, 127.053916)},\r\n");
      out.write("      { latlng: new kakao.maps.LatLng(37.579049, 127.068957)},\r\n");
      out.write("      { latlng: new kakao.maps.LatLng(37.577229, 127.066962)},\r\n");
      out.write("      { latlng: new kakao.maps.LatLng(37.577863, 127.059668)},\r\n");
      out.write("      { latlng: new kakao.maps.LatLng(37.573292, 127.057023)},\r\n");
      out.write("      { latlng: new kakao.maps.LatLng(37.568334, 127.051262)},\r\n");
      out.write("      { latlng: new kakao.maps.LatLng(37.588924, 127.059473)},\r\n");
      out.write("      { latlng: new kakao.maps.LatLng(37.588748, 127.062896)},\r\n");
      out.write("      { latlng: new kakao.maps.LatLng(37.587593, 127.060360)},\r\n");
      out.write("      { latlng: new kakao.maps.LatLng(37.579758, 127.055227)},\r\n");
      out.write("      { latlng: new kakao.maps.LatLng(37.576392, 127.067966)},\r\n");
      out.write("      { latlng: new kakao.maps.LatLng(37.587863, 127.059390)},\r\n");
      out.write("      { latlng: new kakao.maps.LatLng(37.588674, 127.061377)},\r\n");
      out.write("      { latlng: new kakao.maps.LatLng(37.587793, 127.062302)},\r\n");
      out.write("      { latlng: new kakao.maps.LatLng(37.587227, 127.055530)},\r\n");
      out.write("      { latlng: new kakao.maps.LatLng(37.587565, 127.057271)},\r\n");
      out.write("     \r\n");
      out.write("      \r\n");
      out.write("      { latlng: new kakao.maps.LatLng(37.586199, 127.057690)},\r\n");
      out.write("      { latlng: new kakao.maps.LatLng(37.585684, 127.059357)},\r\n");
      out.write("      { latlng: new kakao.maps.LatLng(37.584988, 127.057386)},\r\n");
      out.write("      { latlng: new kakao.maps.LatLng(37.585919, 127.055743)},\r\n");
      out.write("      { latlng: new kakao.maps.LatLng(37.586713, 127.054725)},\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      ];\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("  // 마커 이미지의 이미지 주소입니다\r\n");
      out.write("  var imageSrc = \"http://t1.daumcdn.net/localimg/localimages/07/mapapidoc/markerStar.png\"; \r\n");
      out.write("      \r\n");
      out.write("  for (var i = 0; i < positions.length; i ++) {\r\n");
      out.write("      \r\n");
      out.write("      // 마커 이미지의 이미지 크기 입니다\r\n");
      out.write("      var imageSize = new kakao.maps.Size(34, 45); \r\n");
      out.write("      \r\n");
      out.write("      // 마커 이미지를 생성합니다    \r\n");
      out.write("      var markerImage = new kakao.maps.MarkerImage(imageSrc, imageSize); \r\n");
      out.write("      \r\n");
      out.write("      // 마커를 생성합니다\r\n");
      out.write("      var marker = new kakao.maps.Marker({\r\n");
      out.write("          map: map, // 마커를 표시할 지도\r\n");
      out.write("          position: positions[i].latlng, // 마커를 표시할 위치\r\n");
      out.write("          title : positions[i].title, // 마커의 타이틀, 마커에 마우스를 올리면 타이틀이 표시됩니다\r\n");
      out.write("          image : markerImage // 마커 이미지 \r\n");
      out.write("          \r\n");
      out.write("          \r\n");
      out.write("          \r\n");
      out.write("      });\r\n");
      out.write("  }\r\n");
      out.write("\t\r\n");
      out.write("\t</script>\r\n");
      out.write("  </section>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
