/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.96
 * Generated at: 2019-10-16 02:17:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.boot.test_005ftkdvna;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class tkdvna_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<!-- saved from url=(0083)http://bf.caffebene.co.kr/Content/Gnb/Menu/MenuDetail.aspx?code=T2M3I1&ItemCode=615 -->\r\n");
      out.write("<html><head><meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"><meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scale=no,\"><meta name=\"format-detection\" content=\"telephone=no\"><title>CAFFE BENE</title><link id=\"ctl00_cssInport\" rel=\"stylesheet\" type=\"text/css\" href=\"./tkdvna_files/contents.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"./tkdvna_files/contents_pays.css\">\r\n");
      out.write("    <style>\r\n");
      out.write("        .GnbVisible {\r\n");
      out.write("            display:block;\r\n");
      out.write("            padding:6px 0;\r\n");
      out.write("            line-height : 18px;\r\n");
      out.write("            font-size:12px;\r\n");
      out.write("            color : #ccc;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .TnbVisible {\r\n");
      out.write("            display : block;\r\n");
      out.write("            padding :20px 20px;\r\n");
      out.write("            color : #8c8c8c;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("    <script type=\"text/javascript\" async=\"\" src=\"./tkdvna_files/analytics.js.다운로드\"></script><script src=\"./tkdvna_files/ac.js.다운로드\"></script><script type=\"text/javascript\" src=\"./tkdvna_files/jquery-1.12.3.min.js.다운로드\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"./tkdvna_files/Common.js.다운로드\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"./tkdvna_files/html5.js.다운로드\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"./tkdvna_files/isotope.pkgd.min.js.다운로드\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"./tkdvna_files/swiper.jquery.js.다운로드\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"./tkdvna_files/swipe.js.다운로드\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"./tkdvna_files/style_ui.js.다운로드\"></script>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("        function goMem() {\r\n");
      out.write("            alert(\"이용에 불편을 드려 죄송합니다.\\r\\n회원탈퇴는 카페베네 APP에서 가능하며,\\r\\n문의사항은 고객센터로 연락주시기 바랍니다.\\r\\n(고객센터 : 1688-4666)\");\r\n");
      out.write("        }\r\n");
      out.write("        </script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("        function loginEnd() {\r\n");
      out.write("            alert(\"시스템 점검 중이며 빠른 시일 내 서비스 개선하도록 하겠습니다.\");\r\n");
      out.write("        }\r\n");
      out.write("        </script>\r\n");
      out.write("    \r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("        $(document).ready(function () {\r\n");
      out.write("            otherPrdGallery.init();\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        function goList() {\r\n");
      out.write("            var url = String.format(\"/Content/Gnb/Menu/MenuAll.aspx?code={0}\", qcode);\r\n");
      out.write("\r\n");
      out.write("            $(location).attr('href', url);\r\n");
      out.write("        }\r\n");
      out.write("</script>\r\n");
      out.write("<script src=\"./tkdvna_files/f.txt\"></script></head>\r\n");
      out.write("<body>\r\n");
      out.write("    <form method=\"post\" action=\"http://bf.caffebene.co.kr/Content/Gnb/Menu/MenuDetail.aspx?code=T2M3I1&amp;ItemCode=615\" id=\"aspnetForm\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"pageTitleWrap\">\r\n");
      out.write("\t\t\t<div class=\"pageTitleInner\">\r\n");
      out.write("\t\t\t\t<h2 class=\"pageTit\">커피</h2>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t<!-- //page title &amp; location -->\r\n");
      out.write("\t\t<div id=\"contents\">\r\n");
      out.write("\t\t\t<div class=\"conTitWrap mT0\">\r\n");
      out.write("\t\t\t\t<h3 class=\"tit\">아메리카노(HOT)</h3>\r\n");
      out.write("\t\t\t\t<span class=\"price\"></span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- 메뉴 설명 -->\r\n");
      out.write("\t\t\t<div class=\"prdDetailWrap\">\r\n");
      out.write("\t\t\t\t<div class=\"prdImg\">\r\n");
      out.write("                    <img id=\"ctl00_Contents_imgMenu\" src=\"./tkdvna_files/MenuImage_아메리카노4.png\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"prdSummary\">\r\n");
      out.write("\t\t\t\t\t<div class=\"summInner\">\r\n");
      out.write("\t\t\t\t\t\t<strong class=\"detailTit\">제품특징</strong>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"menuTxt\">\r\n");
      out.write("\t\t\t\t\t\t\t아메리카노\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<strong class=\"detailTit type02\">영양성분</strong>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"viewWrap type02\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<strong class=\"cell_th\">1회 제공량</strong>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"cell_td\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tR1잔(360ml)/L1잔(450ml)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<strong class=\"cell_th\">열량</strong>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"cell_td\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tR13.6/L17.9\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<strong class=\"cell_th\">당류</strong>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"cell_td\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tR0/L0\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<strong class=\"cell_th\">단백질</strong>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"cell_td\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tR1(3%)/L2(4%)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<strong class=\"cell_th\">포화지방</strong>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"cell_td\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tR0.1(0%)/L0.1(1%)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<strong class=\"cell_th\">나트륨</strong>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"cell_td\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tR2(0%)/L2(0%)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- //메뉴 설명 -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"conTitWrap\">\r\n");
      out.write("\t\t\t\t<h3 class=\"tit\">다른제품 보기</h3>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"otherPrdGallery\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btnPrev\"><span class=\"blind\">이전</span></button>\r\n");
      out.write("\t\t\t\t<div class=\"prdGallery swiper-container-horizontal\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"swiper-wrapper\" style=\"width: 8146.4px;\">\r\n");
      out.write("                        \r\n");
      out.write("                                <li class=\"swiper-slide swiper-slide-active\" style=\"width: 239.6px;\">\r\n");
      out.write("\t\t\t\t\t\t\t        <a href=\"http://bf.caffebene.co.kr/Content/Gnb/Menu/MenuDetail.aspx?code=T2M3I1&amp;ItemCode=615\">\r\n");
      out.write("\t\t\t\t\t\t\t\t        <span class=\"img\"><img src=\"./tkdvna_files/MenuImage_아메리카노4(1).png\" alt=\"\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t        <div class=\"prdName\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        <span>아메리카노(HOT)</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        \r\n");
      out.write("\t\t\t\t\t\t\t\t        </div>\r\n");
      out.write("\t\t\t\t\t\t\t        </a>\r\n");
      out.write("\t\t\t\t\t\t        </li>\r\n");
      out.write("                            \r\n");
      out.write("                                <li class=\"swiper-slide swiper-slide-next\" style=\"width: 239.6px;\">\r\n");
      out.write("\t\t\t\t\t\t\t        <a href=\"http://bf.caffebene.co.kr/Content/Gnb/Menu/MenuDetail.aspx?code=T2M3I1&amp;ItemCode=616\">\r\n");
      out.write("\t\t\t\t\t\t\t\t        <span class=\"img\"><img src=\"./tkdvna_files/MenuImage_아이스아메리카노3.png\" alt=\"\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t        <div class=\"prdName\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        <span>아메리카노(ICED)</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        \r\n");
      out.write("\t\t\t\t\t\t\t\t        </div>\r\n");
      out.write("\t\t\t\t\t\t\t        </a>\r\n");
      out.write("\t\t\t\t\t\t        </li>\r\n");
      out.write("                            \r\n");
      out.write("                                <li class=\"swiper-slide\" style=\"width: 239.6px;\">\r\n");
      out.write("\t\t\t\t\t\t\t        <a href=\"http://bf.caffebene.co.kr/Content/Gnb/Menu/MenuDetail.aspx?code=T2M3I1&amp;ItemCode=617\">\r\n");
      out.write("\t\t\t\t\t\t\t\t        <span class=\"img\"><img src=\"./tkdvna_files/MenuImage_에스프레소2.png\" alt=\"\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t        <div class=\"prdName\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        <span>에스프레소</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        Espresso\r\n");
      out.write("\t\t\t\t\t\t\t\t        </div>\r\n");
      out.write("\t\t\t\t\t\t\t        </a>\r\n");
      out.write("\t\t\t\t\t\t        </li>\r\n");
      out.write("                            \r\n");
      out.write("                                <li class=\"swiper-slide\" style=\"width: 239.6px;\">\r\n");
      out.write("\t\t\t\t\t\t\t        <a href=\"http://bf.caffebene.co.kr/Content/Gnb/Menu/MenuDetail.aspx?code=T2M3I1&amp;ItemCode=622\">\r\n");
      out.write("\t\t\t\t\t\t\t\t        <span class=\"img\"><img src=\"./tkdvna_files/MenuImage_아포카또1.png\" alt=\"\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t        <div class=\"prdName\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        <span>아포가또</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        Affogato\r\n");
      out.write("\t\t\t\t\t\t\t\t        </div>\r\n");
      out.write("\t\t\t\t\t\t\t        </a>\r\n");
      out.write("\t\t\t\t\t\t        </li>\r\n");
      out.write("                            \r\n");
      out.write("                                <li class=\"swiper-slide\" style=\"width: 239.6px;\">\r\n");
      out.write("\t\t\t\t\t\t\t        <a href=\"http://bf.caffebene.co.kr/Content/Gnb/Menu/MenuDetail.aspx?code=T2M3I1&amp;ItemCode=623\">\r\n");
      out.write("\t\t\t\t\t\t\t\t        <span class=\"img\"><img src=\"./tkdvna_files/MenuImage_아이스카라멜마키아또.png\" alt=\"\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t        <div class=\"prdName\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        <span>카라멜마끼아또(ICED)</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        Caramel machhiato(ICED)\r\n");
      out.write("\t\t\t\t\t\t\t\t        </div>\r\n");
      out.write("\t\t\t\t\t\t\t        </a>\r\n");
      out.write("\t\t\t\t\t\t        </li>\r\n");
      out.write("                            \r\n");
      out.write("                                <li class=\"swiper-slide\" style=\"width: 239.6px;\">\r\n");
      out.write("\t\t\t\t\t\t\t        <a href=\"http://bf.caffebene.co.kr/Content/Gnb/Menu/MenuDetail.aspx?code=T2M3I1&amp;ItemCode=624\">\r\n");
      out.write("\t\t\t\t\t\t\t\t        <span class=\"img\"><img src=\"./tkdvna_files/MenuImage_카페모카3.png\" alt=\"\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t        <div class=\"prdName\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        <span>카페모카(HOT)</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        Cafe mocha(HOT)\r\n");
      out.write("\t\t\t\t\t\t\t\t        </div>\r\n");
      out.write("\t\t\t\t\t\t\t        </a>\r\n");
      out.write("\t\t\t\t\t\t        </li>\r\n");
      out.write("                            \r\n");
      out.write("                                <li class=\"swiper-slide\" style=\"width: 239.6px;\">\r\n");
      out.write("\t\t\t\t\t\t\t        <a href=\"http://bf.caffebene.co.kr/Content/Gnb/Menu/MenuDetail.aspx?code=T2M3I1&amp;ItemCode=880\">\r\n");
      out.write("\t\t\t\t\t\t\t\t        <span class=\"img\"><img src=\"./tkdvna_files/MenuImage_콜드브루_오리지날프라페노2.png\" alt=\"\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t        <div class=\"prdName\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        <span>오리지날 콜드브루 프라페노</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        Original Cold Brew Frappeno\r\n");
      out.write("\t\t\t\t\t\t\t\t        </div>\r\n");
      out.write("\t\t\t\t\t\t\t        </a>\r\n");
      out.write("\t\t\t\t\t\t        </li>\r\n");
      out.write("                            \r\n");
      out.write("                                <li class=\"swiper-slide\" style=\"width: 239.6px;\">\r\n");
      out.write("\t\t\t\t\t\t\t        <a href=\"http://bf.caffebene.co.kr/Content/Gnb/Menu/MenuDetail.aspx?code=T2M3I1&amp;ItemCode=625\">\r\n");
      out.write("\t\t\t\t\t\t\t\t        <span class=\"img\"><img src=\"./tkdvna_files/MenuImage_아이스카페모카1.png\" alt=\"\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t        <div class=\"prdName\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        <span>카페모카(ICED)</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        Cafe mocha(ICED)\r\n");
      out.write("\t\t\t\t\t\t\t\t        </div>\r\n");
      out.write("\t\t\t\t\t\t\t        </a>\r\n");
      out.write("\t\t\t\t\t\t        </li>\r\n");
      out.write("                            \r\n");
      out.write("                                <li class=\"swiper-slide\" style=\"width: 239.6px;\">\r\n");
      out.write("\t\t\t\t\t\t\t        <a href=\"http://bf.caffebene.co.kr/Content/Gnb/Menu/MenuDetail.aspx?code=T2M3I1&amp;ItemCode=881\">\r\n");
      out.write("\t\t\t\t\t\t\t\t        <span class=\"img\"><img src=\"./tkdvna_files/MenuImage_콜드브루_카라멜프라페노2.png\" alt=\"\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t        <div class=\"prdName\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        <span>콜드브루 카라멜 프라페노</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        Cold Brew Caramel Frappeno\r\n");
      out.write("\t\t\t\t\t\t\t\t        </div>\r\n");
      out.write("\t\t\t\t\t\t\t        </a>\r\n");
      out.write("\t\t\t\t\t\t        </li>\r\n");
      out.write("                            \r\n");
      out.write("                                <li class=\"swiper-slide\" style=\"width: 239.6px;\">\r\n");
      out.write("\t\t\t\t\t\t\t        <a href=\"http://bf.caffebene.co.kr/Content/Gnb/Menu/MenuDetail.aspx?code=T2M3I1&amp;ItemCode=626\">\r\n");
      out.write("\t\t\t\t\t\t\t\t        <span class=\"img\"><img src=\"./tkdvna_files/MenuImage_화이트모카3.png\" alt=\"\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t        <div class=\"prdName\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        <span>화이트모카(HOT)</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        White mocha(HOT)\r\n");
      out.write("\t\t\t\t\t\t\t\t        </div>\r\n");
      out.write("\t\t\t\t\t\t\t        </a>\r\n");
      out.write("\t\t\t\t\t\t        </li>\r\n");
      out.write("                            \r\n");
      out.write("                                <li class=\"swiper-slide\" style=\"width: 239.6px;\">\r\n");
      out.write("\t\t\t\t\t\t\t        <a href=\"http://bf.caffebene.co.kr/Content/Gnb/Menu/MenuDetail.aspx?code=T2M3I1&amp;ItemCode=882\">\r\n");
      out.write("\t\t\t\t\t\t\t\t        <span class=\"img\"><img src=\"./tkdvna_files/MenuImage_콜드브루_화이트모카프라페노2.png\" alt=\"\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t        <div class=\"prdName\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        <span>콜드브루 화이트모카 프라페노</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        Cold Brew White Mocha Frappeno\r\n");
      out.write("\t\t\t\t\t\t\t\t        </div>\r\n");
      out.write("\t\t\t\t\t\t\t        </a>\r\n");
      out.write("\t\t\t\t\t\t        </li>\r\n");
      out.write("                            \r\n");
      out.write("                                <li class=\"swiper-slide\" style=\"width: 239.6px;\">\r\n");
      out.write("\t\t\t\t\t\t\t        <a href=\"http://bf.caffebene.co.kr/Content/Gnb/Menu/MenuDetail.aspx?code=T2M3I1&amp;ItemCode=627\">\r\n");
      out.write("\t\t\t\t\t\t\t\t        <span class=\"img\"><img src=\"./tkdvna_files/MenuImage_아이스화이트모카1.png\" alt=\"\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t        <div class=\"prdName\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        <span>화이트모카(ICED)</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        White mocha(ICED)\r\n");
      out.write("\t\t\t\t\t\t\t\t        </div>\r\n");
      out.write("\t\t\t\t\t\t\t        </a>\r\n");
      out.write("\t\t\t\t\t\t        </li>\r\n");
      out.write("                            \r\n");
      out.write("                                <li class=\"swiper-slide\" style=\"width: 239.6px;\">\r\n");
      out.write("\t\t\t\t\t\t\t        <a href=\"http://bf.caffebene.co.kr/Content/Gnb/Menu/MenuDetail.aspx?code=T2M3I1&amp;ItemCode=883\">\r\n");
      out.write("\t\t\t\t\t\t\t\t        <span class=\"img\"><img src=\"./tkdvna_files/MenuImage_콜드브루_모카프라페노2.png\" alt=\"\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t        <div class=\"prdName\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        <span>콜드브루 모카 프라페노</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        Cold Brew Mocha Frappeno\r\n");
      out.write("\t\t\t\t\t\t\t\t        </div>\r\n");
      out.write("\t\t\t\t\t\t\t        </a>\r\n");
      out.write("\t\t\t\t\t\t        </li>\r\n");
      out.write("                            \r\n");
      out.write("                                <li class=\"swiper-slide\" style=\"width: 239.6px;\">\r\n");
      out.write("\t\t\t\t\t\t\t        <a href=\"http://bf.caffebene.co.kr/Content/Gnb/Menu/MenuDetail.aspx?code=T2M3I1&amp;ItemCode=628\">\r\n");
      out.write("\t\t\t\t\t\t\t\t        <span class=\"img\"><img src=\"./tkdvna_files/MenuImage_바닐라라떼2.png\" alt=\"\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t        <div class=\"prdName\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        <span>바닐라라떼(HOT)</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        Vanilla latte (HOT)\r\n");
      out.write("\t\t\t\t\t\t\t\t        </div>\r\n");
      out.write("\t\t\t\t\t\t\t        </a>\r\n");
      out.write("\t\t\t\t\t\t        </li>\r\n");
      out.write("                            \r\n");
      out.write("                                <li class=\"swiper-slide\" style=\"width: 239.6px;\">\r\n");
      out.write("\t\t\t\t\t\t\t        <a href=\"http://bf.caffebene.co.kr/Content/Gnb/Menu/MenuDetail.aspx?code=T2M3I1&amp;ItemCode=884\">\r\n");
      out.write("\t\t\t\t\t\t\t\t        <span class=\"img\"><img src=\"./tkdvna_files/MenuImage_콜드블루 카라멜마끼야또 저용량2.png\" alt=\"\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t        <div class=\"prdName\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        <span>콜드브루 카라멜마끼아또</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        Cold Brew Caramel machhiato\r\n");
      out.write("\t\t\t\t\t\t\t\t        </div>\r\n");
      out.write("\t\t\t\t\t\t\t        </a>\r\n");
      out.write("\t\t\t\t\t\t        </li>\r\n");
      out.write("                            \r\n");
      out.write("                                <li class=\"swiper-slide\" style=\"width: 239.6px;\">\r\n");
      out.write("\t\t\t\t\t\t\t        <a href=\"http://bf.caffebene.co.kr/Content/Gnb/Menu/MenuDetail.aspx?code=T2M3I1&amp;ItemCode=629\">\r\n");
      out.write("\t\t\t\t\t\t\t\t        <span class=\"img\"><img src=\"./tkdvna_files/MenuImage_라떼.png\" alt=\"\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t        <div class=\"prdName\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        <span>바닐라라떼(ICED)</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        Vanilla latte (ICED)\r\n");
      out.write("\t\t\t\t\t\t\t\t        </div>\r\n");
      out.write("\t\t\t\t\t\t\t        </a>\r\n");
      out.write("\t\t\t\t\t\t        </li>\r\n");
      out.write("                            \r\n");
      out.write("                                <li class=\"swiper-slide\" style=\"width: 239.6px;\">\r\n");
      out.write("\t\t\t\t\t\t\t        <a href=\"http://bf.caffebene.co.kr/Content/Gnb/Menu/MenuDetail.aspx?code=T2M3I1&amp;ItemCode=885\">\r\n");
      out.write("\t\t\t\t\t\t\t\t        <span class=\"img\"><img src=\"./tkdvna_files/MenuImage_콜드블루 아메리카노 저용량2.png\" alt=\"\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t        <div class=\"prdName\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        <span>콜드브루</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        Cold Brew\r\n");
      out.write("\t\t\t\t\t\t\t\t        </div>\r\n");
      out.write("\t\t\t\t\t\t\t        </a>\r\n");
      out.write("\t\t\t\t\t\t        </li>\r\n");
      out.write("                            \r\n");
      out.write("                                <li class=\"swiper-slide\" style=\"width: 239.6px;\">\r\n");
      out.write("\t\t\t\t\t\t\t        <a href=\"http://bf.caffebene.co.kr/Content/Gnb/Menu/MenuDetail.aspx?code=T2M3I1&amp;ItemCode=630\">\r\n");
      out.write("\t\t\t\t\t\t\t\t        <span class=\"img\"><img src=\"./tkdvna_files/MenuImage_카페라떼.png\" alt=\"\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t        <div class=\"prdName\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        <span>카페라떼(HOT)</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        Caffe latte(HOT)\r\n");
      out.write("\t\t\t\t\t\t\t\t        </div>\r\n");
      out.write("\t\t\t\t\t\t\t        </a>\r\n");
      out.write("\t\t\t\t\t\t        </li>\r\n");
      out.write("                            \r\n");
      out.write("                                <li class=\"swiper-slide\" style=\"width: 239.6px;\">\r\n");
      out.write("\t\t\t\t\t\t\t        <a href=\"http://bf.caffebene.co.kr/Content/Gnb/Menu/MenuDetail.aspx?code=T2M3I1&amp;ItemCode=887\">\r\n");
      out.write("\t\t\t\t\t\t\t\t        <span class=\"img\"><img src=\"./tkdvna_files/MenuImage_나이트로 콜드브루 누끼2.png\" alt=\"\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t        <div class=\"prdName\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        <span>나이트로 콜드브루</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        Nitro Cold Brew\r\n");
      out.write("\t\t\t\t\t\t\t\t        </div>\r\n");
      out.write("\t\t\t\t\t\t\t        </a>\r\n");
      out.write("\t\t\t\t\t\t        </li>\r\n");
      out.write("                            \r\n");
      out.write("                                <li class=\"swiper-slide\" style=\"width: 239.6px;\">\r\n");
      out.write("\t\t\t\t\t\t\t        <a href=\"http://bf.caffebene.co.kr/Content/Gnb/Menu/MenuDetail.aspx?code=T2M3I1&amp;ItemCode=632\">\r\n");
      out.write("\t\t\t\t\t\t\t\t        <span class=\"img\"><img src=\"./tkdvna_files/MenuImage_카푸치노1.png\" alt=\"\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t        <div class=\"prdName\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        <span>카푸치노</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        Cappuccino\r\n");
      out.write("\t\t\t\t\t\t\t\t        </div>\r\n");
      out.write("\t\t\t\t\t\t\t        </a>\r\n");
      out.write("\t\t\t\t\t\t        </li>\r\n");
      out.write("                            \r\n");
      out.write("                                <li class=\"swiper-slide\" style=\"width: 239.6px;\">\r\n");
      out.write("\t\t\t\t\t\t\t        <a href=\"http://bf.caffebene.co.kr/Content/Gnb/Menu/MenuDetail.aspx?code=T2M3I1&amp;ItemCode=888\">\r\n");
      out.write("\t\t\t\t\t\t\t\t        <span class=\"img\"><img src=\"./tkdvna_files/MenuImage_콜드브루헤이즐넛라떼.png\" alt=\"\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t        <div class=\"prdName\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        <span>콜드브루 헤이즐넛라떼</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        Cold Brew Hazelnut latte\r\n");
      out.write("\t\t\t\t\t\t\t\t        </div>\r\n");
      out.write("\t\t\t\t\t\t\t        </a>\r\n");
      out.write("\t\t\t\t\t\t        </li>\r\n");
      out.write("                            \r\n");
      out.write("                                <li class=\"swiper-slide\" style=\"width: 239.6px;\">\r\n");
      out.write("\t\t\t\t\t\t\t        <a href=\"http://bf.caffebene.co.kr/Content/Gnb/Menu/MenuDetail.aspx?code=T2M3I1&amp;ItemCode=889\">\r\n");
      out.write("\t\t\t\t\t\t\t\t        <span class=\"img\"><img src=\"./tkdvna_files/MenuImage_콜드브루바닐라젤라또라떼.png\" alt=\"\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t        <div class=\"prdName\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        <span>콜드브루 바닐라젤라또 라떼</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        Cold Brew Vanilla Gelato latte\r\n");
      out.write("\t\t\t\t\t\t\t\t        </div>\r\n");
      out.write("\t\t\t\t\t\t\t        </a>\r\n");
      out.write("\t\t\t\t\t\t        </li>\r\n");
      out.write("                            \r\n");
      out.write("                                <li class=\"swiper-slide\" style=\"width: 239.6px;\">\r\n");
      out.write("\t\t\t\t\t\t\t        <a href=\"http://bf.caffebene.co.kr/Content/Gnb/Menu/MenuDetail.aspx?code=T2M3I1&amp;ItemCode=922\">\r\n");
      out.write("\t\t\t\t\t\t\t\t        <span class=\"img\"><img src=\"./tkdvna_files/MenuImage_마끼아토1.png\" alt=\"\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t        <div class=\"prdName\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        <span>카라멜마끼아또(HOT)</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        Caramel Machhiato(HOT)\r\n");
      out.write("\t\t\t\t\t\t\t\t        </div>\r\n");
      out.write("\t\t\t\t\t\t\t        </a>\r\n");
      out.write("\t\t\t\t\t\t        </li>\r\n");
      out.write("                            \r\n");
      out.write("                                <li class=\"swiper-slide\" style=\"width: 239.6px;\">\r\n");
      out.write("\t\t\t\t\t\t\t        <a href=\"http://bf.caffebene.co.kr/Content/Gnb/Menu/MenuDetail.aspx?code=T2M3I1&amp;ItemCode=951\">\r\n");
      out.write("\t\t\t\t\t\t\t\t        <span class=\"img\"><img src=\"./tkdvna_files/MenuImage_브라운슈가 콜드브루 펄라떼.png\" alt=\"\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t        <div class=\"prdName\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        <span>브라운슈가 콜드브루 펄라떼</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        Brown Sugar Coldbrew Pearl Latte\r\n");
      out.write("\t\t\t\t\t\t\t\t        </div>\r\n");
      out.write("\t\t\t\t\t\t\t        </a>\r\n");
      out.write("\t\t\t\t\t\t        </li>\r\n");
      out.write("                            \r\n");
      out.write("                                <li class=\"swiper-slide\" style=\"width: 239.6px;\">\r\n");
      out.write("\t\t\t\t\t\t\t        <a href=\"http://bf.caffebene.co.kr/Content/Gnb/Menu/MenuDetail.aspx?code=T2M3I1&amp;ItemCode=965\">\r\n");
      out.write("\t\t\t\t\t\t\t\t        <span class=\"img\"><img src=\"./tkdvna_files/MenuImage_아이스라떼.png\" alt=\"\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t        <div class=\"prdName\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        <span>카페라떼(ICED)</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        Caffe Latte(ICED)\r\n");
      out.write("\t\t\t\t\t\t\t\t        </div>\r\n");
      out.write("\t\t\t\t\t\t\t        </a>\r\n");
      out.write("\t\t\t\t\t\t        </li>\r\n");
      out.write("                            \r\n");
      out.write("                                <li class=\"swiper-slide\" style=\"width: 239.6px;\">\r\n");
      out.write("\t\t\t\t\t\t\t        <a href=\"http://bf.caffebene.co.kr/Content/Gnb/Menu/MenuDetail.aspx?code=T2M3I1&amp;ItemCode=968\">\r\n");
      out.write("\t\t\t\t\t\t\t\t        <span class=\"img\"><img src=\"./tkdvna_files/MenuImage_플랫화이트.png\" alt=\"\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t        <div class=\"prdName\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        <span>플랫화이트(HOT)</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        Flat White\r\n");
      out.write("\t\t\t\t\t\t\t\t        </div>\r\n");
      out.write("\t\t\t\t\t\t\t        </a>\r\n");
      out.write("\t\t\t\t\t\t        </li>\r\n");
      out.write("                            \r\n");
      out.write("                                <li class=\"swiper-slide\" style=\"width: 239.6px;\">\r\n");
      out.write("\t\t\t\t\t\t\t        <a href=\"http://bf.caffebene.co.kr/Content/Gnb/Menu/MenuDetail.aspx?code=T2M3I1&amp;ItemCode=969\">\r\n");
      out.write("\t\t\t\t\t\t\t\t        <span class=\"img\"><img src=\"./tkdvna_files/MenuImage_시나몬라떼.png\" alt=\"\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t        <div class=\"prdName\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        <span>플레어 시나몬라떼(HOT)</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        Flair Cinnamon Latte(HOT)\r\n");
      out.write("\t\t\t\t\t\t\t\t        </div>\r\n");
      out.write("\t\t\t\t\t\t\t        </a>\r\n");
      out.write("\t\t\t\t\t\t        </li>\r\n");
      out.write("                            \r\n");
      out.write("                                <li class=\"swiper-slide\" style=\"width: 239.6px;\">\r\n");
      out.write("\t\t\t\t\t\t\t        <a href=\"http://bf.caffebene.co.kr/Content/Gnb/Menu/MenuDetail.aspx?code=T2M3I1&amp;ItemCode=970\">\r\n");
      out.write("\t\t\t\t\t\t\t\t        <span class=\"img\"><img src=\"./tkdvna_files/MenuImage_연유라떼.png\" alt=\"\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t        <div class=\"prdName\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        <span>플레어 연유라떼(HOT)</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        Flair Condensed Milk Latte\r\n");
      out.write("\t\t\t\t\t\t\t\t        </div>\r\n");
      out.write("\t\t\t\t\t\t\t        </a>\r\n");
      out.write("\t\t\t\t\t\t        </li>\r\n");
      out.write("                            \r\n");
      out.write("                                <li class=\"swiper-slide\" style=\"width: 239.6px;\">\r\n");
      out.write("\t\t\t\t\t\t\t        <a href=\"http://bf.caffebene.co.kr/Content/Gnb/Menu/MenuDetail.aspx?code=T2M3I1&amp;ItemCode=971\">\r\n");
      out.write("\t\t\t\t\t\t\t\t        <span class=\"img\"><img src=\"./tkdvna_files/MenuImage_연유라떼아이스.png\" alt=\"\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t        <div class=\"prdName\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        <span>플레어 연유라떼(ICE)</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        Flair Condensed Milk Latte \r\n");
      out.write("\t\t\t\t\t\t\t\t        </div>\r\n");
      out.write("\t\t\t\t\t\t\t        </a>\r\n");
      out.write("\t\t\t\t\t\t        </li>\r\n");
      out.write("                            \r\n");
      out.write("                                <li class=\"swiper-slide\" style=\"width: 239.6px;\">\r\n");
      out.write("\t\t\t\t\t\t\t        <a href=\"http://bf.caffebene.co.kr/Content/Gnb/Menu/MenuDetail.aspx?code=T2M3I1&amp;ItemCode=868\">\r\n");
      out.write("\t\t\t\t\t\t\t\t        <span class=\"img\"><img src=\"./tkdvna_files/MenuImage_콜드블루라떼 저용량2.png\" alt=\"\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t        <div class=\"prdName\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        <span>콜드브루라떼</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        Cold Brew latte\r\n");
      out.write("\t\t\t\t\t\t\t\t        </div>\r\n");
      out.write("\t\t\t\t\t\t\t        </a>\r\n");
      out.write("\t\t\t\t\t\t        </li>\r\n");
      out.write("                            \r\n");
      out.write("                                <li class=\"swiper-slide\" style=\"width: 239.6px;\">\r\n");
      out.write("\t\t\t\t\t\t\t        <a href=\"http://bf.caffebene.co.kr/Content/Gnb/Menu/MenuDetail.aspx?code=T2M3I1&amp;ItemCode=916\">\r\n");
      out.write("\t\t\t\t\t\t\t\t        <span class=\"img\"><img src=\"./tkdvna_files/MenuImage_아인슈페너1.png\" alt=\"\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t        <div class=\"prdName\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        <span>흑당 아인슈페너(HOT)</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        Black Sugar Einspanner(HOT)\r\n");
      out.write("\t\t\t\t\t\t\t\t        </div>\r\n");
      out.write("\t\t\t\t\t\t\t        </a>\r\n");
      out.write("\t\t\t\t\t\t        </li>\r\n");
      out.write("                            \r\n");
      out.write("                                <li class=\"swiper-slide\" style=\"width: 239.6px;\">\r\n");
      out.write("\t\t\t\t\t\t\t        <a href=\"http://bf.caffebene.co.kr/Content/Gnb/Menu/MenuDetail.aspx?code=T2M3I1&amp;ItemCode=917\">\r\n");
      out.write("\t\t\t\t\t\t\t\t        <span class=\"img\"><img src=\"./tkdvna_files/MenuImage_아인슈페너.png\" alt=\"\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t        <div class=\"prdName\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        <span>흑당 아인슈페너(ICE)</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        Black Sugar Einspanner(ICE)\r\n");
      out.write("\t\t\t\t\t\t\t\t        </div>\r\n");
      out.write("\t\t\t\t\t\t\t        </a>\r\n");
      out.write("\t\t\t\t\t\t        </li>\r\n");
      out.write("                            \r\n");
      out.write("                                <li class=\"swiper-slide\" style=\"width: 239.6px;\">\r\n");
      out.write("\t\t\t\t\t\t\t        <a href=\"http://bf.caffebene.co.kr/Content/Gnb/Menu/MenuDetail.aspx?code=T2M3I1&amp;ItemCode=918\">\r\n");
      out.write("\t\t\t\t\t\t\t\t        <span class=\"img\"><img src=\"./tkdvna_files/MenuImage_아인슈페너라떼2.png\" alt=\"\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t        <div class=\"prdName\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        <span>흑당 아인슈페너 라떼(HOT)</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        Black Sugar Einspanner Latte(HOT)\r\n");
      out.write("\t\t\t\t\t\t\t\t        </div>\r\n");
      out.write("\t\t\t\t\t\t\t        </a>\r\n");
      out.write("\t\t\t\t\t\t        </li>\r\n");
      out.write("                            \r\n");
      out.write("                                <li class=\"swiper-slide\" style=\"width: 239.6px;\">\r\n");
      out.write("\t\t\t\t\t\t\t        <a href=\"http://bf.caffebene.co.kr/Content/Gnb/Menu/MenuDetail.aspx?code=T2M3I1&amp;ItemCode=919\">\r\n");
      out.write("\t\t\t\t\t\t\t\t        <span class=\"img\"><img src=\"./tkdvna_files/MenuImage_아인슈페너라떼.png\" alt=\"\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t        <div class=\"prdName\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        <span>흑당 아인슈페너 라떼(ICE)</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        Black Sugar Einspanner Latte(ICE)\r\n");
      out.write("\t\t\t\t\t\t\t\t        </div>\r\n");
      out.write("\t\t\t\t\t\t\t        </a>\r\n");
      out.write("\t\t\t\t\t\t        </li>\r\n");
      out.write("                            \r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btnNext\"><span class=\"blind\">다음</span></button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"btnPageWrap\">\r\n");
      out.write("\t\t\t\t<!-- <a href=\"http://bf.caffebene.co.kr/Content/Gnb/Menu/MenuDetail.aspx?code=T2M3I1&amp;ItemCode=615#\" class=\"btn02\" onclick=\"goList();\">목록</a> -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- //container -->\r\n");
      out.write("\r\n");
      out.write("            <div class=\"btnGoTop\">\r\n");
      out.write("        \t\t<a href=\"http://bf.caffebene.co.kr/Content/Gnb/Menu/MenuDetail.aspx?code=T2M3I1&amp;ItemCode=615#\">TOP</a>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\r\n");
      out.write("\t   \r\n");
      out.write("\r\n");
      out.write("</body></html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
